### ISSUE TITLE
Метод public int play(Game game, int hours) не суммирует часы игры

### ISSUE THREAD

**Issue by TanjaDalvadiants** [TanjaDalvadiants/GameTracker#10]
# Описание
Метод public int play(Game game, int hours)не считает общую сумму "Часов" всех "Игр"
 "игрока"

# Локация дефекта
https://github.com/TanjaDalvadiants/GameTracker/blob/5455b55c4585592e14c8543a5daf77c020d934f8/src/main/java/ru/netology/Player.java#L40

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TanjaDalvadiants/GameTracker/blob/player/src/test/java/netology/PlayerTest.java) в IDEA
2. Вызвать метод public int play(Game game, int hours) 
3. Запустить тест
4. Посмотреть вывод в консоли

*Ожидаемый результат:* Программа считает общую сумму часов всех игр
Вывод в консоли
Expected:6
Actual:6

*Фактический результат:* Вывод в консоли
Expected:6
Actual:0

# Скриншот
![Monosnap GameTracker – PlayerTest java 2023-03-26 10-29-17](https://user-images.githubusercontent.com/121951420/227759424-c2d1d758-a987-4d67-b700-ff16ec353ab5.jpg)

# Окружение
_Операционная система:_ macOS 13.01
_IDE:_ IntelliJ IDEA 2022.3.1
_Java:_ OpenJDK 11

**Comment by annakainova** [comment]
Fixed
