### ISSUE TITLE
Игра не находится с помощью поиска в каталоге игр

### ISSUE THREAD

**Issue by annakainova** [TanjaDalvadiants/GameTracker#2]
# Описание
При попытке найти игру, которая есть в каталоге, метод containsGame() не находит игру и возвращает false

# Локация дефекта
https://github.com/TanjaDalvadiants/GameTracker/blob/5455b55c4585592e14c8543a5daf77c020d934f8/src/main/java/ru/netology/GameStore.java#L33

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TanjaDalvadiants/GameTracker/blob/main/src/test/java/netology/GameStoreTest.java) в IDEA
2. Добавить игру в каталог с помощью метода publishGame()
3. Вызвать метод containsGame() в виде добавленной игры
4. Запустить тест
5. Посмотреть вывод в консоли

*Ожидаемый результат:* игра найдена в каталоге, метод containsGame() возвращает true
*Фактический результат:* игра не найдена в каталоге, метод containsGame() возвращает false

# Скриншот
![image](https://user-images.githubusercontent.com/122302380/226950019-e86b3781-b5bf-4b79-83e1-b607e7810e6e.png)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA 2022.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by TanjaDalvadiants** [comment]
Fixed
