### ISSUE TITLE
Метод суммарного расчета времени игры всех игроков возвращает 0

### ISSUE THREAD

**Issue by annakainova** [TanjaDalvadiants/GameTracker#3]
# Описание
Метод getSumPlayedTime() возвращает 0 вместо подсчета суммарного времени игры всех игроков

# Локация дефекта
https://github.com/TanjaDalvadiants/GameTracker/blob/5455b55c4585592e14c8543a5daf77c020d934f8/src/main/java/ru/netology/GameStore.java#L76

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TanjaDalvadiants/GameTracker/blob/main/src/test/java/netology/GameStoreTest.java) в IDEA
2. Добавить время игры для игрока1 и игрока 2 по 3 и 6 часов соответственно
3. Вызвать метод getSumPlayedTime() для того, чтобы получить общее количество часов игры
4. Запустить тест
5. Посмотреть вывод в консоли

*Ожидаемый результат:* общее время игры для игроков составляет 9 часов
*Фактический результат:* общее время игры для игроков составляет 0 часов

# Скриншот
![image](https://user-images.githubusercontent.com/122302380/226953690-05a426d7-6d5e-4682-ae4d-773032b87102.png)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA 2022.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by TanjaDalvadiants** [comment]
Fixed
