### ISSUE TITLE
Метод getMostPlayer() возвращает null, если игрок поиграл всего 1 час

### ISSUE THREAD

**Issue by annakainova** [TanjaDalvadiants/GameTracker#4]
# Описание
Метод getMostPlayer() возвращает null, если игрок только один и он играл в игру всего 1 час

# Локация дефекта
https://github.com/TanjaDalvadiants/GameTracker/blob/5455b55c4585592e14c8543a5daf77c020d934f8/src/main/java/ru/netology/GameStore.java#L59

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TanjaDalvadiants/GameTracker/blob/main/src/test/java/netology/GameStoreTest.java) в IDEA
2. Добавить время игры для игрока1 1 час
3. Вызвать метод getMostPlayer() для того, чтобы получить имя игрока, который играл наибольшее количество часов
4. Запустить тест
5. Посмотреть вывод в консоли

*Ожидаемый результат:* метод возвращает имя игрока1
*Фактический результат:* метод возвращает имя null

# Скриншот
![image](https://user-images.githubusercontent.com/122302380/226956450-9a19185e-80fa-46db-8d99-a4a1e84ef874.png)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA 2022.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by TanjaDalvadiants** [comment]
Fixed
