### ISSUE TITLE
Время игроков, проведенное в игре, не суммируется

### ISSUE THREAD

**Issue by annakainova** [TanjaDalvadiants/GameTracker#5]
# Описание
Метод addPlayTime() не суммирует время игрока, проведенное за игрой
# Локация дефекта
https://github.com/TanjaDalvadiants/GameTracker/blob/5455b55c4585592e14c8543a5daf77c020d934f8/src/main/java/ru/netology/GameStore.java#L48

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TanjaDalvadiants/GameTracker/blob/main/src/test/java/netology/GameStoreTest.java) в IDEA
2. Добавить время игры для игрока1 последовательно, например 1,3,5 и 1 час. Добавить время для игрока2 5 и 1 час
3. Вызвать метод getMostPlayer() для того, чтобы получить игрока с раибольшим часлом часов
4. Запустить тест
5. Посмотреть вывод в консоли

*Ожидаемый результат:* метод возвращает имя игрока1 (его общее количество часов 10)
*Фактический результат:* метод возвращает имя игрока2 (программа считает, что общее количество часов игрока1 = 1, а игрока 2 = 5)

# Скриншот
![image](https://user-images.githubusercontent.com/122302380/226966343-4e6137ba-544c-4d32-aed7-e5d1602103d2.png)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA 2022.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by TanjaDalvadiants** [comment]
Fixed
