### ISSUE TITLE
Общее время игры у игр одного "Жанра" не суммируется

### ISSUE THREAD

**Issue by TanjaDalvadiants** [TanjaDalvadiants/GameTracker#6]
# Описание 
 Общее время игры игр, отсортированных по "Жанру" не суммируется.

![Monosnap GameTracker – PlayerTest java 2023-03-23 13-50-38](https://user-images.githubusercontent.com/121951420/227166199-9f9bd574-bc4a-4c06-a185-e07d0c1d3a72.jpg)

# Локация дефекта
https://github.com/TanjaDalvadiants/GameTracker/blob/5455b55c4585592e14c8543a5daf77c020d934f8/src/main/java/ru/netology/Player.java#L49

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/TanjaDalvadiants/GameTracker/blob/player/src/test/java/netology/PlayerTest.java) в IDEA
3. Запустить программу
4. Посмотреть вывод на консоли

_Ожидаемый результат:_ Программа считает количество часов игры всех игроков во все игры по входному параметру "Жанр".

В консоли должно отображаться.
Expected :3
Actual   :3

_Фактический результат:_  В консоли всегда отображается 0.
В консоли отображается:
Expected :3
Actual   :0

# Окружение
_Операционная система:_ macOS 13.01
_IDE:_ IntelliJ IDEA 2022.3.1
_Java:_ OpenJDK 11

**Comment by annakainova** [comment]
Fixed
