### ISSUE TITLE
Метод public Game mostPlayerByGenre(String genre) всегда возвращает null

### ISSUE THREAD

**Issue by TanjaDalvadiants** [TanjaDalvadiants/GameTracker#7]
# Описание 
В методе не прописано условие, отличное от null. 
Результат метода всегда  null.

![Monosnap GameTracker – Player java 2023-03-23 14-02-36](https://user-images.githubusercontent.com/121951420/227170134-57753567-13c2-4a39-93dc-5e244cb4ce6f.jpg)

# Локация дефекта
https://github.com/TanjaDalvadiants/GameTracker/blob/5455b55c4585592e14c8543a5daf77c020d934f8/src/main/java/ru/netology/Player.java#L60

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/TanjaDalvadiants/GameTracker/blob/player/src/test/java/netology/PlayerTest.java) в IDEA
2. Запустить программу
3. Посмотреть вывод на консоли

_Ожидаемый результат:_ Программа  находит "Игрока" , игравшего дольше всего "Часов" в игру заданного "Жанра"
В консоли должно отображаться.
Expected: game1
Actual: "Аркады"

_Фактический результат:_  
В консоли отображается:
![Monosnap GameTracker – PlayerTest java 2023-03-26 12-14-04](https://user-images.githubusercontent.com/121951420/227763654-e7e6499d-e87a-47db-aa54-c9a7066e99d2.jpg)

# Окружение
_Операционная система:_ macOS 13.01
_IDE:_ IntelliJ IDEA 2022.3.1
_Java:_ OpenJDK 11

**Comment by annakainova** [comment]
Fixed
