### ISSUE TITLE
Класс NotFoundException  не создан

### ISSUE THREAD

**Issue by TanjaDalvadiants** [TanjaDalvadiants/GameTracker#8]
# Описание
По тз метод public int play(Game game, int hours) должен использовать класс NotFoundException,  если игра не была установлена игроком.
![Monosnap GameTracker – Player java 2023-03-23 14-17-34](https://user-images.githubusercontent.com/121951420/227173574-772f9dc5-1c95-4128-8ba0-001b67f72106.jpg)

# Локация дефекта
https://github.com/TanjaDalvadiants/GameTracker/blob/5455b55c4585592e14c8543a5daf77c020d934f8/src/main/java/ru/netology/Player.java#L38

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TanjaDalvadiants/GameTracker/blob/player/src/test/java/netology/PlayerTest.java) в IDEA
2. Добавить неустановленную игру
3. Вызвать метод public int play(Game game, int hours) для того, чтобы получить сообщение NotFoundException.
4. Запустить тест
5. Посмотреть вывод в консоли

*Ожидаемый результат:* Программа выкидывает оповещение, что заданная игра не установлена.
*Фактический результат:* Вывод в консоли
![Monosnap GameTracker – PlayerTest java 2023-03-26 12-02-05](https://user-images.githubusercontent.com/121951420/227763245-8d61e733-ce3f-4d5f-bea7-6a2bc281f575.jpg)

# Окружение
_Операционная система:_ macOS 13.01
_IDE:_ IntelliJ IDEA 2022.3.1
_Java:_ OpenJDK 11

**Comment by annakainova** [comment]
Fixed
